services:

  order-service:
    build: ./services/order-service
    container_name: order-service
    ports:
      - "8080:8080"

  payment-service:
    build: ./services/payment-service
    container_name: payment-service
    ports:
      - "8081:8080"    

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--log.level=warn'  
    depends_on:
      - order-service
      - payment-service
    
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_LOG_LEVEL=warn
     