services:

  postgres:
    image: postgres:18-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data_v18:/var/lib/postgresql

  order-service:
    build: ./services/order-service
    container_name: order-service
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_JWKS_URI=http://keycloak:8080/realms/example/protocol/openid-connect/certs
      - APP_SERVICES_PAYMENT_URL=http://payment-service:8080/api
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/orderdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - postgres
      - keycloak

  payment-service:
    build: ./services/payment-service
    container_name: payment-service
    ports:
      - "8081:8080"    
    environment:
      - KEYCLOAK_JWKS_URI=http://keycloak:8080/realms/example/protocol/openid-connect/certs
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/paymentdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - postgres
      - keycloak

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
    - "--config.file=/etc/prometheus/prometheus.yml"
    - '--log.level=warn'  
    depends_on:
      - order-service
      - payment-service
    
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_LOG_LEVEL=warn

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: keycloak
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8082:8080"
    volumes:
      - ./keycloak/example-realm.json:/opt/keycloak/data/import/example-realm.json:ro

volumes:
  postgres_data_v18:
     