plugins {
    id 'java-library'
    id 'io.spring.dependency-management'
}

group = 'com.example.platform.exceptions'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

dependencies {
    implementation libs.spring.boot.starter.web
    compileOnly libs.spring.boot.starter.security
    compileOnly libs.spring.boot.starter.validation
    compileOnly libs.lombok
    annotationProcessor libs.lombok
}
