[versions]
spring-boot = "4.0.6"
micrometerTracing = "1.3.5"
opentelemetry = "1.38.0"


[libraries]
# ✅ Correct Key: spring-boot-starter-web
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "spring-boot" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator", version.ref = "spring-boot" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring-boot" }
spring-boot-starter-aspectj = { module = "org.springframework.boot:spring-boot-starter-aspectj", version.ref = "spring-boot" }
spring-boot-config-processor = { module = "org.springframework.boot:spring-boot-configuration-processor", version.ref = "spring-boot" }

# Other dependencies
micrometer-prometheus = { module = "io.micrometer:micrometer-registry-prometheus", version = "1.13.0" }
lombok = { module = "org.projectlombok:lombok", version = "1.18.34" }
logstash-logback-encoder = { module = "net.logstash.logback:logstash-logback-encoder", version = "7.4" } # Use latest version
micrometer-tracing-bridge-otel = { group = "io.micrometer", name = "micrometer-tracing-bridge-otel", version.ref = "micrometerTracing" }
opentelemetry-exporter-otlp = { group = "io.opentelemetry", name = "opentelemetry-exporter-otlp", version.ref = "opentelemetry" }


[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
dependency-management = { id = "io.spring.dependency-management", version = "1.1.5" }   