server:
  servlet:
    context-path: /api

spring:
  application:
    name: payment-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:8082/realms/example/protocol/openid-connect/certs}

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"

logging:
  pattern:
    level: "%5p [traceId=%X{traceId}]"

app:
  env: dev
  region: india
