plugins {
    id 'java-library'   // ✅ Correct for shared libraries
    id 'io.spring.dependency-management'
}

group = 'com.example.platfrom.observability'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

dependencies {
    // ✅ EXPOSED
    api libs.spring.boot.starter.aspectj
    api libs.micrometer.tracing.bridge.otel
    api libs.micrometer.prometheus

    // ✅ INTERNAL
    implementation libs.spring.boot.starter.web
    implementation libs.spring.boot.starter.actuator
    implementation libs.logstash.logback.encoder
    implementation libs.opentelemetry.exporter.otlp

    annotationProcessor libs.spring.boot.config.processor
    compileOnly libs.spring.boot.config.processor
}
