
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"      

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.boot.actuate: INFO
    com.example.platform.observability: INFO

  pattern:
    level: "%5p [traceId=%X{traceId}]"


app:
  env: dev
  region: india  

spring:
  application:
    name: order-service

server:
  servlet:
    context-path: /api 
  
