management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  pattern:
    level: "%5p [traceId=%X{traceId}]"
app:
  env: dev
  region: india  
spring:
  application:
    name: order-service
