
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"      

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.boot.actuate: INFO
    com.example.platform.observability: INFO

  pattern:
    level: "%5p [traceId=%X{traceId}]"


app:
  env: dev
  region: india  

spring:
  application:
    name: order-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:8082/realms/example/protocol/openid-connect/certs}

server:
  servlet:
    context-path: /api 
  
