server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: order-service-actuator
              uri: http://order-service:8080
              predicates:
                - Path=/api/orders/actuator/**
              filters:
                - RewritePath=/api/orders/actuator/(?<segment>.*),/api/actuator/\${segment}
              order: 1
            - id: order-service
              uri: http://order-service:8080
              predicates:
                - Path=/api/orders/**
              order: 2

            - id: payment-service-actuator
              uri: http://payment-service:8080
              predicates:
                - Path=/api/payments/actuator/**
              filters:
                - RewritePath=/api/payments/actuator/(?<segment>.*),/api/actuator/\${segment}
              order: 3
            - id: payment-service
              uri: http://payment-service:8080
              predicates:
                - Path=/api/payments/**
              order: 4

            - id: notification-service-actuator
              uri: http://notification-service:8080
              predicates:
                - Path=/api/notifications/actuator/**
              filters:
                - RewritePath=/api/notifications/actuator/(?<segment>.*),/api/actuator/\${segment}
              order: 5
            - id: notification-service
              uri: http://notification-service:8080
              predicates:
                - Path=/api/notifications/**
              order: 6

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
